services:
  db:
    image: postgres:latest
    restart: always
    container_name: graphqlauthcont
    ports:
      - '5442:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=authgraphqldb
